name: inventory_scanner
description: "A barcode inventory scanning application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_settings_screens: ^0.3.4
  scoped_model: ^2.0.0
  ftpconnect: ^2.0.7
  http: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  csv: ^5.1.1
  share_plus: ^7.2.1
  cupertino_icons: ^1.0.8
  mobile_scanner: ^6.0.5
  wakelock_plus: ^1.2.10
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true